server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**

        - id: transaction-service
          uri: http://localhost:8081
          predicates:
            - Path=/transactions/**
